# Generated by Django 2.1.1 on 2018-09-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180902_0049'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_groups',
            field=models.ManyToManyField(to='main.CustomGroup'),
        ),
    ]
