# Generated by Django 2.1.1 on 2018-09-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180902_0049'),
        ('users', '0002_customuser_custom_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='posts',
            field=models.ManyToManyField(to='main.Post'),
        ),
    ]
