# Generated by Django 2.1.1 on 2018-09-02 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='posts',
            new_name='posts_to_show',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='test_text',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='friend_requests_received',
            field=models.ManyToManyField(related_name='_customuser_friend_requests_received_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='friend_requests_sent',
            field=models.ManyToManyField(related_name='_customuser_friend_requests_sent_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(related_name='_customuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
