# Generated by Django 2.1.1 on 2018-09-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180903_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='friend_requests_received',
        ),
    ]
