# Generated by Django 2.1.1 on 2018-09-03 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180903_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friend_requests_sent',
            field=models.ManyToManyField(blank=True, related_name='_customuser_friend_requests_sent_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
