# Generated by Django 2.1.1 on 2018-09-03 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180903_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friend_requests_sent',
            field=models.ManyToManyField(blank=True, related_name='_customuser_friend_requests_sent_+', related_query_name='friend_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
