# Generated by Django 2.1.1 on 2018-09-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180905_1933'),
        ('users', '0013_auto_20180903_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='main.Post'),
        ),
    ]
