# Generated by Django 2.1.1 on 2018-09-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_notification_for_post'),
        ('users', '0014_customuser_liked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='starred_posts',
            field=models.ManyToManyField(blank=True, related_name='starred_by', to='main.Post'),
        ),
    ]
