# Generated by Django 2.1.1 on 2018-10-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180911_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.png', null=True, upload_to='avatars/'),
        ),
    ]
