# Generated by Django 2.1.1 on 2018-09-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180902_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CustomGroup'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=5000),
        ),
    ]
