# Generated by Django 2.1.1 on 2018-09-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180903_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-added']},
        ),
    ]
