# Generated by Django 2.1.1 on 2018-09-03 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20180903_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='groups_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='group_photos/'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='posts',
            field=models.ManyToManyField(null=True, to='main.Post'),
        ),
    ]
