# Generated by Django 2.1.1 on 2018-09-03 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180903_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
