# Generated by Django 2.1.1 on 2018-09-05 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20180904_0216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'ordering': ['-last_activity_date']},
        ),
        migrations.AddField(
            model_name='customgroup',
            name='users',
            field=models.ManyToManyField(null=True, related_name='groups_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='admins',
            field=models.ManyToManyField(related_name='groups_admin_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
