# Generated by Django 2.1.1 on 2018-09-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180905_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='users',
            new_name='members',
        ),
    ]
