# Generated by Django 2.1.1 on 2018-09-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180905_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={},
        ),
        migrations.AddField(
            model_name='customgroup',
            name='to_approve',
            field=models.ManyToManyField(null=True, related_name='posts_to_approve', to='main.Post'),
        ),
    ]
