# Generated by Django 2.1.1 on 2018-09-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['added']},
        ),
    ]
