# Generated by Django 2.1.1 on 2018-09-09 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_notification_for_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='tagged_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
