# Generated by Django 2.1.1 on 2018-09-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180913_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='for_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_to', to='main.CustomGroup'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='for_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Post'),
        ),
    ]
