# Generated by Django 2.1.1 on 2018-09-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180913_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='for_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='invited_to', to='main.CustomGroup'),
        ),
    ]
