# Generated by Django 2.1.1 on 2018-09-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['creation_date']},
        ),
    ]
